### PR TITLE
Add support for HTTPS

### PR DESCRIPTION
**Pull request by Kris-LIBIS**
Check if URI scheme is 'https' and set :use_ssl to true.

### CODE REVIEW

**Comment by edsu** [comment]
Hi @Kris-LIBIS. Unfortunately I no longer use Ruby or SRU and was wondering if you might be interested in taking over maintenance of the package? I could transfer the GitHub repository to you and add your account to the [rubygems project](https://rubygems.org/gems/sru)? Let me know!

**Comment by Kris-LIBIS** [comment]
@edsu Yes, please. We are actively using ruby and SRU, so I would be interested in maintaining the gem.

**Comment by edsu** [comment]
Great, what is your rubygems username?

**Comment by edsu** [comment]
Also, for me to transfer to you on GitHub I think you will need to rename your clone to `sru-ruby-old` or something. I am getting an error that the repository already exists when I try to transfer.

**Comment by Kris-LIBIS** [comment]
My account name on Rubygems.org is KRIS-LIBIS and I also renamed my fork.

**Pull request merged**
